### ISSUE TITLE
build error on gcc 7.2

### ISSUE THREAD

**Issue by sk0427** [Santy-8128/Minimac3#8]
I tried build with gcc 7.2.0. However, I found an error below
```
Parameters.cpp: In member function ‘virtual void LongParameters::Status()’:
Parameters.cpp:573:25: error: use of an operand of type ‘bool’ in ‘operator++’ is deprecated [-Werror=deprecated]
             legacy_count++;
                         ^~
cc1plus: all warnings being treated as errors
make[3]: *** [obj/Parameters.o] Error 1
make[2]: *** [general] Error 2
make[1]: *** [../Library/libStatGenForMinimac3/libStatGen.a] Error 2
make[1]: Leaving directory `/home/Minimac3/src'
make: *** [src] Error 2
```

I replaced 

```
Minimac3/Library/libStatGenForMinimac3/general
```

with

```
libStatGen/general (cloned from https://github.com/statgen/libStatGen.git)
```

and it was successfully build.
But, does it works well?

**Comment by Santy-8128** [comment]
Hi, Yes, that should work perfect. Sorry about the delay in response.
